POST  http://localhost:8888/api/add_query/

[
    {
    "name": "list student",
    "conn": "demo",
    "sql": "select name, age, school_id from student",
    "path": "student/list"
    },
    {
    "name": "create student",
    "conn": "demo",
    "sql": "insert into student (`name`, `age`, `school_id`) values (@name, @age, @school_id)",
    "path": "student/create"
    }
]

###

GET http://localhost:8888/brand


###
POST http://localhost:8888/api/add_conn
Content-Type: application/json

{
    "uri": "sqlite://local.db",
    "name": "local"
}

###
POST  http://localhost:8888/api/add_query
Content-Type: application/json

[
    {
    "name": "sqlite",
    "conn": "local",
    "sql": "select * from COMPANY;",
    "path": "student/list"
    }
]

###

POST http://localhost:8888/api/add_conn
Content-Type: application/json

[   {
        "uri": "mysql://root:1234TttT@localhost:3306/mysql",
        "name": "test_mysql"
    },
    {
        "uri": "sqlite://local.db",
        "name": "local"
    }
]

###

POST  http://localhost:8888/api/add_query
Content-Type: application/json

[
    {
        "name": "test_mysql",
        "conn": "test_mysql",
        "sql": "select * from db;",
        "path": "test_mysql"
    },
    {
        "name": "whoami",
        "conn": "test_mysql",
        "sql": "SELECT `table_name` AS `name`, `engine`\nFROM information_schema\nWHERE `table_type` = 'BASE TABLE`\nORDER BY `name`",
        "path": "whoami"
    },
    {
        "name": "whoami_sqlite",
        "conn": "local",
        "sql": "select 'main' AS `database`;",
        "path": "whoami_sqlite"
    },
    {
        "name": "sqlite pragma",
        "conn": "local",
        "sql": "--? table: str // 表名称\nSELECT `name` AS `column_name`, `dflt_value` AS `default_value`, `notnull` AS `is_nullable`, `type`, `pk`\nFROM pragma_table_info(@table)",
        "path": "sqlite_pragma"
    }
]

###
GET http://localhost:8888/api/explore/status